require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BusinessTypesController do

  # This should return the minimal set of attributes required to create a valid
  # BusinessType. As you add validations to BusinessType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all business_types as @business_types" do
      business_type = BusinessType.create! valid_attributes
      get :index
      assigns(:business_types).should eq([business_type])
    end
  end

  describe "GET show" do
    it "assigns the requested business_type as @business_type" do
      business_type = BusinessType.create! valid_attributes
      get :show, :id => business_type.id
      assigns(:business_type).should eq(business_type)
    end
  end

  describe "GET new" do
    it "assigns a new business_type as @business_type" do
      get :new
      assigns(:business_type).should be_a_new(BusinessType)
    end
  end

  describe "GET edit" do
    it "assigns the requested business_type as @business_type" do
      business_type = BusinessType.create! valid_attributes
      get :edit, :id => business_type.id
      assigns(:business_type).should eq(business_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BusinessType" do
        expect {
          post :create, :business_type => valid_attributes
        }.to change(BusinessType, :count).by(1)
      end

      it "assigns a newly created business_type as @business_type" do
        post :create, :business_type => valid_attributes
        assigns(:business_type).should be_a(BusinessType)
        assigns(:business_type).should be_persisted
      end

      it "redirects to the created business_type" do
        post :create, :business_type => valid_attributes
        response.should redirect_to(BusinessType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved business_type as @business_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessType.any_instance.stub(:save).and_return(false)
        post :create, :business_type => {}
        assigns(:business_type).should be_a_new(BusinessType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessType.any_instance.stub(:save).and_return(false)
        post :create, :business_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested business_type" do
        business_type = BusinessType.create! valid_attributes
        # Assuming there are no other business_types in the database, this
        # specifies that the BusinessType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BusinessType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => business_type.id, :business_type => {'these' => 'params'}
      end

      it "assigns the requested business_type as @business_type" do
        business_type = BusinessType.create! valid_attributes
        put :update, :id => business_type.id, :business_type => valid_attributes
        assigns(:business_type).should eq(business_type)
      end

      it "redirects to the business_type" do
        business_type = BusinessType.create! valid_attributes
        put :update, :id => business_type.id, :business_type => valid_attributes
        response.should redirect_to(business_type)
      end
    end

    describe "with invalid params" do
      it "assigns the business_type as @business_type" do
        business_type = BusinessType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessType.any_instance.stub(:save).and_return(false)
        put :update, :id => business_type.id, :business_type => {}
        assigns(:business_type).should eq(business_type)
      end

      it "re-renders the 'edit' template" do
        business_type = BusinessType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessType.any_instance.stub(:save).and_return(false)
        put :update, :id => business_type.id, :business_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested business_type" do
      business_type = BusinessType.create! valid_attributes
      expect {
        delete :destroy, :id => business_type.id
      }.to change(BusinessType, :count).by(-1)
    end

    it "redirects to the business_types list" do
      business_type = BusinessType.create! valid_attributes
      delete :destroy, :id => business_type.id
      response.should redirect_to(business_types_url)
    end
  end

end
